### ISSUE TITLE
how to setup provisioning

### ISSUE THREAD

**Issue by ZerataX** [mautrix/telegram#487]
Fairly sure I had this working at some point, but now I'm very confused what the base url should look like. This is what I have it currently set to:

```yaml
provisioning:
  enabled: true
  prefix: /_matrix/appservice-telegram/provision/v1
```

![comparison dimension config to mautrix](https://user-images.githubusercontent.com/5024958/85210392-af163080-b33f-11ea-858d-ef5fe2603352.png)

Also tried to test it with:
https://spec.maunium.net/mxtg-provisioning/#/

But this doesn't allow me to change the base url.

should it work like this, given my reverse proxy is correctly setup and I copied the shared secret correctly?
