### ISSUE TITLE
How to use provisioning API? Got 404 on any endpoint

### ISSUE THREAD

**Issue by rakshazi** [mautrix/telegram#589]
Hello,
trying to configure Provisioning API for my homeserver with following mautrix-telegram config:

```yml
appservice:
    address: http://matrix-mautrix-telegram:8080
    as_token: REDACTED
    bot_avatar: mxc://maunium.net/tJCRmUyJDsgRNgqhOgoiHWbX
    bot_displayname: Telegram bridge bot
    bot_username: telegrambot
    database: postgres://REDACTED
    hostname: 0.0.0.0
    hs_token: REDACTED
    id: telegram
    max_body_size: 1
    port: 8080
    provisioning:
        enabled: true
        prefix: /_matrix/provision/v1
        shared_secret: REDACTED
    public:
        enabled: true
        external: https://REDACTED/REDACTED_PUBLIC_PREFIX
        prefix: /REDACTED_PUBLIC_PREFIX
```

Following requests don't work (actually, any other request does not work):

```bash
curl -X GET "https://REDACTED/_matrix/provision/v1/bridge" -H "accept: application/json" -H "Authorization: Bearer REDACTED"

<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>Sorry. No luck finding that resource.</p>
  </body>
</html>
```

```bash
curl -X GET "https://REDACTED/REDACTED_PUBLIC_PREFIX/provision/v1/bridge" -H "accept: application/json" -H "Authorization: Bearer REDACTED"

404: Not Found
```

Could you explain how should I configure and access the provisioning API endpoints, please?
