### ISSUE TITLE
Problem with whitelist

### ISSUE THREAD

**Issue by SF2311** [mautrix/telegram#784]
Hello everyone,

I've set up the bridge using the [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) ansible playbook.
The bridge is configured to run in relay mode, which works fine.
The problem arises if I try to invite a user from another matrix server into the room. Immediately after the user is joined, they are kicked by the bridge bot with the message:
`You are not whitelisted on this Telegram bridge.`
I've traced this error message to the code introduced in [f7ac86ee3b4625df31c6575ddf1de6abe3c873c0](https://github.com/mautrix/telegram/commit/f7ac86ee3b4625df31c6575ddf1de6abe3c873c0) but I don't exactly understand what's going on there.
The relevant portion of the config is as far as I understand the following:
```yaml
relaybot:
        authless_portals: true
        group_chat_invite: []
        ignore_own_incoming_events: true
        ignore_unbridged_group_chat: true
        private_chat:
            invite: []
            message: This is a Matrix bridge relaybot and does not support direct
                chats
            state_changes: true
        whitelist: []
        whitelist_group_admins: true
```
I could not find any documentation on this whitelist feature and its behavior, so what do I need to change in order to get it working?
